export const menuData = {
  viennoiserie: [
    { name: "PAIN SUISSE", price: "6,00 DH" },
    { name: "PAIN SUISSE NOIX", price: "7,00 DH" },
    { name: "PAIN VANILLE", price: "7,00 DH" },
    { name: "SCHNECK RAISIN", price: "6,00 DH" },
    { name: "CROISSANT SÉSAME NOIR", price: "8,00 DH" },
    { name: "CROISSANT SIMPLE", price: "4,50 DH" },
    { name: "CROISSANT AUX AMANDES", price: "8,00 DH" },
    { name: "DOUBLE SCHNECK CHOCOLAT", price: "6,00 DH" },
    { name: "FORÊT FRAMBOISE", price: "8,00 DH" },
    { name: "FORÊT PISTACHIER", price: "8,00 DH" },
    { name: "PAIN CÉRÉALES", price: "7,00 DH" },
    { name: "FORÊT KNAFEH PISTACHIER", price: "10,00 DH" },
    { name: "FORÊT NUTELLA", price: "8,00 DH" },
    { name: "PAPILLON FRAMBOISE", price: "8,00 DH" },
    { name: "PASTEIS DE NATA", price: "10,00 DH" },
    { name: "NEW-YORK ROLL", price: "16,00 DH" },
    { name: "AMERICAN", price: "8,00 DH" },
    { name: "BRIOCHE FARCIE", price: "5,00 DH" },
    { name: "BRIOCHE FEUILLÉ", price: "15,00 DH" },
    { name: "BRIOCHE NORMALE", price: "3,00 DH" },
    { name: "BRIOCHE RECIPE", price: "5,00 DH" },
    { name: "BRIOCHE SIMPLE", price: "4,00 DH" },
    { name: "DANISH", price: "8,00 DH" },
    { name: "DANISH STRIÉ", price: "10,00 DH" },
    { name: "DONUTS", price: "10,00 DH" },
    { name: "FORÊT FANCIE", price: "8,00 DH" }
  ],
  articlesSales: [
    { name: "CHAUSSON FROMAGE", price: "10,00 DH" },
    { name: "CHAWARMA POULET", price: "10,00 DH" },
    { name: "MILLE-FEUILLE FRUITS", price: "15,00 DH" },
    { name: "PAIN DE MIE THON", price: "10,00 DH" },
    { name: "PIZZA POULET-SAUCE FROMAGE", price: "10,00 DH" },
    { name: "PIZZA THON", price: "10,00 DH" },
    { name: "QUICHE 3 FROMAGES", price: "12,00 DH" },
    { name: "QUICHE SAUMON", price: "13,00 DH" },
    { name: "SALADE ROUGE-TOMATE-CRIS", price: "25,00 DH" },
    { name: "SANDWICH POULET", price: "12,00 DH" },
    { name: "SANDWICH THON", price: "10,00 DH" },
    { name: "VOLAUVENT POULET", price: "10,00 DH" },
    { name: "WRAP CHICKEN", price: "12,00 DH" },
    { name: "BZAYTMAJ POULET KIRI", price: "10,00 DH" },
    { name: "CREPE CHARCUTERIE", price: "10,00 DH" },
    { name: "CROQUE FROMAGE", price: "6,00 DH" },
    { name: "BRIOUATES POISSON", price: "10,00 DH" },
    { name: "BZAITMAT POULET KIRI", price: "10,00 DH" },
    { name: "NEMS VIANDE HACHÉE", price: "8,00 DH" },
    { name: "NEMS IMANSI", price: "8,00 DH" },
    { name: "PASTILLA POULET IV", price: "10,00 DH" },
    { name: "RGHAYEFAT THON", price: "7,00 DH" },
    { name: "BRAYWAT TANJIA", price: "10,00 DH" },
    { name: "BRAYWAT THON", price: "9,00 DH" },
    { name: "PASTILLA POULET", price: "12,00 DH" },
    { name: "NEMS ÉPINARD SAUMON", price: "10,00 DH" },
    { name: "NEMS ÉMINCÉ", price: "10,00 DH" },
    { name: "BRIWAT POISSON", price: "10,00 DH" }
  ],
  plateaux: [
    { name: "MINI PLATEAU BELDI MAROC", price: "50,00" },
    { name: "MINI PLATEAU BURGER COLORÉ", price: "150,00" },
    { name: "MINI PLATEAU CANAPE", price: "150,00" },
    { name: "MINI PLATEAU DONUTS", price: "75,00" },
    { name: "MINI PLATEAU FRANCAISE", price: "100,00" },
    { name: "MINI PLATEAU MACARON", price: "175,00" },
    { name: "MINI PLATEAU MIELLE-FEUIL", price: "175,00" },
    { name: "MINI PLATEAU SALE MAROCAINE", price: "125,00" },
    { name: "MINI PLATEAU SOIREE", price: "110,00" },
    { name: "MINI PLATEAU TARTELETTES", price: "110,00" },
    { name: "MINI PLATEAU VERRINE", price: "175,00" },
    { name: "MINI PLATEAU VIENNOISERIE", price: "75,00" },
    { name: "MINI PLATEAU MACARON Sucrée", price: "175,00" },
    { name: "PLATEAU BELDI MAROCAIN", price: "100,00" },
    { name: "PLATEAU BURGER COLORÉ", price: "300,00" },
    { name: "PLATEAU CANAPE", price: "300,00" },
    { name: "PLATEAU DONUITS", price: "150,00" },
    { name: "PLATEAU FRANCAISE", price: "200,00" },
    { name: "PLATEAU MACARON SALE", price: "350,00" },
    { name: "PLATEAU MACARON SUCRE", price: "350,00" },
    { name: "PLATEAU MIEL FEUILLE SO", price: "350,00" },
    { name: "PLATEAU SALE MAROCAIN", price: "250,00" },
    { name: "PLATEAU SOIREE", price: "220,00" },
    { name: "PLATEAU TARTELETTES", price: "350,00" },
    { name: "PLATEAU VERRINES SALE", price: "350,00" },
    { name: "PLATEAU VIENNOISERIE", price: "150,00" }
  ],
  patisserie: [
    { name: "WEDDING", price: "29,00" },
    { name: "CITRON", price: "28,00" },
    { name: "MANGO", price: "35,00" },
    { name: "OPERA 4 SAISONS", price: "28,00" },
    { name: "VANILLE", price: "29,00" },
    { name: "NINOU", price: "39,00" },
    { name: "YUZU", price: "29,00" },
    { name: "GOUGOU", price: "29,00" },
    { name: "FLOWER", price: "35,00" },
    { name: "POP-CORN", price: "39,00" },
    { name: "PISTACHE", price: "35,00" },
    { name: "TOUT CHOCOLAT", price: "29,00" },
    { name: "ICE HAWAII", price: "28,00" },
    { name: "LETICIA", price: "28,00" },
    { name: "PUSH NOISETTE", price: "28,00" },
    { name: "ENTREMETS NORMAL", price: "250,00" },
    { name: "ENTREMETS HAUTE GAMME", price: "500,00" },
    { name: "SIGNATURE CABALLERO", price: "35,00" },
    { name: "SNICKERS", price: "28,00" },
    { name: "SOLERO", price: "34,00" },
    { name: "BROWNIES", price: "16,00" },
    { name: "CAKE DATES", price: "15,00" },
    { name: "CAKE CAROTTE", price: "15,00" },
    { name: "CAKE CHMONIX", price: "15,00" },
    { name: "CAKE CHOCOLAT", price: "15,00" },
    { name: "CAKE HONEY", price: "20,00" },
    { name: "CAKE CARAMEL", price: "18,00" },
    { name: "CAKE MIEL", price: "15,00" }
  ]
}
